theme: jekyll-theme-minimal  
title: "MMLoSo Workshop @ IJCNP-AACL 2025"  
description: "First International Workshop on Multimodal Models for Low-Resource Contexts and Social Impact"  
github: false 

